spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_match_system
    username: root
    password: 123456
  # 解决SpringBoot版本号>=2.6时和Swagger整合的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    database: 0 # 可不写，默认就是0
  session:
    timeout: 86400 # 单位秒，这里是1天
    store-type: redis # 使用redis存储用户登录信息，实现分布式系统共享。

server:
  servlet:
    # 指定项目根路径
    context-path: /api
    # 设置cookie只在localhost域名有效
    session:
      cookie:
        domain: localhost
  port: 8080

mybatis-plus:
  configuration:
    # 关闭下划线和驼峰自动转换
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志打印
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)